.PHONY: clean All

All:
	@echo "----------Building project:[ Hummingbird - Debug ]----------"
	@"$(MAKE)" -f  "Hummingbird.mk"
clean:
	@echo "----------Cleaning project:[ Hummingbird - Debug ]----------"
	@"$(MAKE)" -f  "Hummingbird.mk" clean
